version: "3"

services:
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - "vaalikoppi-redis:/data"

  vaalikoppi:
    image: prodekoregistry.azurecr.io/vaalikoppi/vaalikoppi:latest
    restart: unless-stopped
    command: gunicorn election.wsgi:application -b 0.0.0.0:8001
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=election.settings.prod
      - SECRET_KEY=ANSIBLE_REPLACE_SECRET_KEY
      - DB_PASSWORD=ANSIBLE_REPLACE_DB_PASSWORD
      - DB_USER=user_vaalikoppi@prodeko-postgres
      - POSTGRESQL_SSL_CA=/code/ca-certs/CombinedCa.crt.pem
      - SENTRY_DSN=https://dda0512eee65464c893202702005be39@sentry.prodeko.org/4

volumes:
  vaalikoppi-redis:
    external: true

networks:
  default:
    external:
      name: prodeko-docker-net
