name: Deploy

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run docker-compose stack
        run: docker-compose up -d

      # Should not do it like this...
      - name: Sleep for 15 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "15s"

      - name: Run linters
        run: docker exec vaalikoppi npm run eslint && npm run curlylint

      - name: Run tests
        run: docker exec vaalikoppi pytest --cov --cov-report=xml election/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests

      - name: Sentry release
        uses: getsentry/action-release@v1.1.2
        env:
          SENTRY_URL: https://sentry.prodeko.org/
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: prodeko
          SENTRY_PROJECT: vaalikoppi
        with:
          environment: production
